version: "2.2"
services:
  jobmanager:
    image: flink:1.11.0-scala_2.11
    ports:
      - "8081:8081"
    command: standalone-job --job-classname ilegra.ApplicationJob
    volumes:
      - /home/thiago/projects/ilegra-test/build/libs:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: flink:1.11.0-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - /home/thiago/projects/ilegra-test/build/libs:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2